<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $this->call(UsersTableSeeder::class);
         $this->call('ColorTableSeeder');
    }
}

class ProductTableSeeder extends Seeder
{

    public function run()
    {
       DB::table('product')->insert([
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2),
               array('name'=>'quan thun', 'price'=>'50000','cate_id'=>2),
               array('name'=>'quan dai', 'price'=>'52000','cate_id'=>2),
               array('name'=>'quan ngo', 'price'=>'55000','cate_id'=>2),
               array('name'=>'quan sip', 'price'=>'57000','cate_id'=>2)

       ]
       );
    }
}

class ThemesTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('themes')->insert([
                array('name'=>'quanthun.jpg', 'product_id'=>2),
                array('name'=>'quandai.jpg', 'product_id'=>2),
                array('name'=>'quanngo.jpg', 'product_id'=>3),
                array('name'=>'quansip.jpg', 'product_id'=>3)
            ]
        );
    }
}

class CarTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('cars')->insert([
                array('name'=>'mercedes', 'price'=>'50000000'),
                array('name'=>'hyundai', 'price'=>'52000000'),
                array('name'=>'bucati', 'price'=>'55000000'),
                array('name'=>'honda', 'price'=>'57000000')
            ]
        );
    }
}

class ColorTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('colors')->insert([
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
                array('name'=>'red'),
                array('name'=>'green'),
                array('name'=>'blue'),
                array('name'=>'yellow'),
            ]
        );
    }
}

class Car_ColorTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('car__color')->insert([
                array('car_id'=>'1', 'color_id'=>'2'),
                array('car_id'=>'1', 'color_id'=>'4'),
                array('car_id'=>'2', 'color_id'=>'4'),
                array('car_id'=>'2', 'color_id'=>'1')
            ]
        );
    }
}

class ThanhVienTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('thanhviens')->insert([
                array('user'=>'teo', 'pass'=>Hash::make(12345), 'level'=>1),
                array('user'=>'tun', 'pass'=>Hash::make(12345), 'level'=>1),
                array('user'=>'tuan', 'pass'=>Hash::make(12345), 'level'=>1),
            ]
        );
    }
}